### ISSUE TITLE
Potential problem with the #present method when overriding #initialize in a presenter

### ISSUE THREAD

**Issue by finn-francis** [samsarge/presenter-rails#5]
If #initialize is overriden with extra arguments in a presenter, it could possibly break the present method.
e.g.
```ruby
def initialize(user, first_name)
  user.first_name = first_name
  super user
end
```

To fix this we could add an options hash for #present

**Comment by finn-francis** [comment]
[This](https://github.com/samsarge/presenter-rails/pull/6) pull request should solve this issue

**Comment by samsarge** [comment]
Finished [here](https://github.com/samsarge/presenter-rails/pull/6)
